# Generated by Django 6.1 on 2026-08-11 23:16

import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Texte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categorie', models.CharField(choices=[('poeme', 'Poème'), ('blog', 'Blog'), ('roman', 'Roman')], max_length=20)),
                ('contenu', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Contenu')),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='couvertures/')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Fichier PDF')),
                ('publie', models.BooleanField(default=False)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, to='contenu.tag')),
            ],
        ),
    ]
